apiVersion: v1
kind: Service
metadata:
  name: {{ include "yildizdb.fullname" . }}
  labels:
    app: {{ include "yildizdb.name" . }}
    chart: {{ include "yildizdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "yildizdb.name" . }}
    release: {{ .Release.Name }}
